server:
  port: 8383

spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
#    OSIV는 기본이 true
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
logging:
  level:
    root: debug
#    개발시에는 debug 운영시에는 info